name: Build and Check Docker Compose

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:latest
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Build and start containers
        run: docker-compose up -d --build

      - name: Wait for DB to be healthy
        run: |
          for i in {1..10}; do
            if docker-compose exec -T db pg_isready -U user; then
              echo "Database is ready."
              exit 0
            fi
            echo "Waiting for db..."
            sleep 5
          done
          echo "Database not ready in time."
          docker-compose logs
          exit 1

      - name: Check app container logs
        run: docker-compose logs app
